var shuffleSequence= seq("consent","intro1","intro2","spk0","p1","intro3","p2","p3","intro4","b1_spk","b1_i1","b1_i2","b1_i3","b1_i4","b1_i5","b1_i6","b1_i7","b1_i8","b1_i9","b1_i10","b1_i11","b1_i12","b1_i13","b1_i14","b1_i15","b1_i16","b1_i17","b1_i18","b1_i19","b1_i20","b1_i21","b2_spk","b2_i1","b2_i2","b2_i3","b2_i4","b2_i5","b2_i6","b2_i7","b2_i8","b2_i9","b2_i10","b2_i11","b2_i12","b2_i13","b2_i14","b2_i15","b2_i16","b2_i17","b2_i18","b2_i19","b2_i20","b2_i21","b3_spk","b3_i1","b3_i2","b3_i3","b3_i4","b3_i5","b3_i6","b3_i7","b3_i8","b3_i9","b3_i10","b3_i11","b3_i12","b3_i13","b3_i14","b3_i15","b3_i16","b3_i17","b3_i18","b3_i19","b3_i20","b3_i21","b4_spk","b4_i1","b4_i2","b4_i3","b4_i4","b4_i5","b4_i6","b4_i7","b4_i8","b4_i9","b4_i10","b4_i11","b4_i12","b4_i13","b4_i14","b4_i15","b4_i16","b4_i17","b4_i18","b4_i19","b4_i20","b4_i21","break","b5_spk","b5_i1","b5_i2","b5_i3","b5_i4","b5_i5","b5_i6","b5_i7","b5_i8","b5_i9","b5_i10","b5_i11","b5_i12","b5_i13","b5_i14","b5_i15","b5_i16","b5_i17","b5_i18","b5_i19","b5_i20","b5_i21","b6_spk","b6_i1","b6_i2","b6_i3","b6_i4","b6_i5","b6_i6","b6_i7","b6_i8","b6_i9","b6_i10","b6_i11","b6_i12","b6_i13","b6_i14","b6_i15","b6_i16","b6_i17","b6_i18","b6_i19","b6_i20","b6_i21","b7_spk","b7_i1","b7_i2","b7_i3","b7_i4","b7_i5","b7_i6","b7_i7","b7_i8","b7_i9","b7_i10","b7_i11","b7_i12","b7_i13","b7_i14","b7_i15","b7_i16","b7_i17","b7_i18","b7_i19","b7_i20","b7_i21","b8_spk","b8_i1","b8_i2","b8_i3","b8_i4","b8_i5","b8_i6","b8_i7","b8_i8","b8_i9","b8_i10","b8_i11","b8_i12","b8_i13","b8_i14","b8_i15","b8_i16","b8_i17","b8_i18","b8_i19","b8_i20","b8_i21","lhq");

var practiceItemTypes = ["practice"];
var centerItems = true;
var completionMessage = "Results sent to server. Your completion code is PNItUHdEk$.";
var sendingResultsMessage = "Sending results to server. This may take a little while-- leave this window open until results are sent!";


var defaults = [
    "Separator", {
        transfer: 500, //wait for 1000ms
          //other options: "keypress", "click"
        normalMessage: " ", //message to be displayed
        errorMessage: "Incorrect" //message to be displayed in red
    },

    "Message", {
        //"html" option is obligatory
        hideProgressBar: true,
        saveReactionTime: true,
        transfer: "keypress"
    },

    "Email", {
        hideProgressBar: true,
        transfer: 2500,
        hasCorrect: false,
        instructions: "Press space to read message"
    },

    "DashedSentence", {
        //"s" option is obligatory
        hideProgressBar: true,
        mode: "self-paced reading"
          //other option: "speeded acceptability"
    },

    "Question", {
        //"as" option is obligatory
        as: ["Yes", "No"],
        hideProgressBar: true,
        hasCorrect: false,
        presentHorizontally: true,
        randomOrder: false
          //if a question has a correct answer,
            //keep it as the first element of the "as" option
    },

    "Form", {
        //"html" option is obligatory
        hideProgressBar: true,
        saveReactionTime: true
    }
];

var items = [

    /*
    ===================
    SEPARATOR
    The pause needed between each item of the experiment
    ===================
    */

    //ends after timer (1000ms)
    ["sep", "Separator", {transfer: 1000, normalMessage: "+"}],

    /*
    ===================
    INTRODUCTION
    Can include files for Questionnaires, consent forms etc...
    ===================
    */

    //name of controller
    ["consent", "Form", {html: { include: "consent.html" } } ],
    
    ["intro1", "Form", {html: { include: "captchas.html" } } ],

	["intro2", "Message", {html: { include: "instr1.html" } } ],

    ["spk0", "Message", {html: { include: 'Speaker0.html' }, transfer: 14000, hideProgressBar: false}],

    ["p1", "Message", {html: { include: "instr2.html" } }, 
    "Email", {s1: "Message from Emily", s2: "RE: breakfast", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/emily-bubble-1gn8tl7.jpg"]]}, 
    "Message", {html: { include: "instr3.html" } }, 
    "DashedSentence", {s: "my favorite cereal is lucky charms."},
    "Message", {html: { include: "instr4.html" } }, 
    "Question", {q: "Are Cheerios Emily's favorite??", as: [["F","F   .   Yes"],["J","J   .   No"]], hasCorrect: 1}, "Separator", {normalMessage: "Correct"}],

	["intro3", "Message", {html: { include: "instr5.html" } } ],

     ["p2", "Email", {s1: "Message from Emily", s2: "RE: pets", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/emily-bubble-1gn8tl7.jpg"]]}, "DashedSentence", {s: "i have a pet dog and a pet cat."}, "Question", {q: "Does Emily have a cat?", as: [["F","F   .   Yes"],["J","J   .   No"]], hasCorrect: 0}, "Separator",{normalMessage: "Correct"}],
    
     ["p3", "Email", {s1: "Message from Emily", s2: "RE: overslept", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/emily-bubble-1gn8tl7.jpg"]]}, "DashedSentence", {s: "ugh I can't seem to get up for my 9am class."}, "Question", {q: "Does Emily find it easy to get to her morning class?", as: [["F","F   .   Yes"],["J","J   .   No"]], hasCorrect: 1},"Separator",{normalMessage: "Correct"}],    

	["intro4", "Message", {html: { include: "instr6.html" } } ],
["b1_i1", "Email", {s1: "Message from Tiffany", s2: "RE: a few plot spoilers", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "in the movie the uncle of the milkman who had to support himself with a low income liked to fish."}, "Question", {q: "Was it the milkman who was self-supporting?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i10", "Email", {s1: "Message from Tiffany", s2: "RE: horse", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "he said that an old woman rescued a cow from nearly crashing into a fence."}, "Question", {q: "Did the cow crash in to the fence?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i11", "Email", {s1: "Message from Tiffany", s2: "RE: news article", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "I read in the news that the talented photographers accepted the money could not be spent yet."}, "Question", {q: "Did someone spend the money too soon?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i12", "Email", {s1: "Message from Tiffany", s2: "RE: what a jerk", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "why cant he keep his nose in his own business!"}, "Question", {q: "Is Tiffany angry at someone?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i13", "Email", {s1: "Message from Tiffany", s2: "RE: can't believe I bought cable", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "there's nothing on tv tonihgt, what are you watching?"}, "Question", {q: "Is Tiffany looking for something to watch?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i14", "Email", {s1: "Message from Tiffany", s2: "RE: soap opera = guilty pleasure", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "in the show the grandmother of the stewardess who treated herself to an ice cream cone was waiting at home."}, "Question", {q: "Was it the grandmother who had an ice cream cone?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i15", "Email", {s1: "Message from Tiffany", s2: "RE: no way", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "I read that a babysitter kept a baby from surely suffocating in the old crib."}, "Question", {q: "Did the baby suffocate in the old crib?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i16", "Email", {s1: "Message from Tiffany", s2: "RE: after the meeting", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "I heard the suggestion to the directors totally were made after the meeting."}, "Question", {q: "Was there more than one suggestion after the meeting?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i17", "Email", {s1: "Message from Tiffany", s2: "RE: yayy!", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "my bff is coming up to visit me this weekend."}, "Question", {q: "Did Tiffany make plans with a friend?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i18", "Email", {s1: "Message from Tiffany", s2: "RE: thunderstorm", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "yesterday afternoon the grandmother stopped an umbrella from surely flying away in the wind."}, "Question", {q: "Did the umbrella fly away in the wind?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i19", "Email", {s1: "Message from Tiffany", s2: "RE: skype Wednesday", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "my parents lost the password for their skype account again."}, "Question", {q: "Is Tiffany better at using the computer than some of her family members?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i2", "Email", {s1: "Message from Tiffany", s2: "RE: exercise", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "he saw that Lulu visited the gym without her hat on late yesterday night."}, "Question", {q: "Was Lulu wearing her hat when she visited the gym?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i20", "Email", {s1: "Message from Tiffany", s2: "RE: all set", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "no really the microphone for the singer finally was on the stand."}, "Question", {q: "Was there more than one microphone on the stand?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i21", "Email", {s1: "Message from Tiffany", s2: "RE: super nice", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "he heard that the medal for the winners literally were on the podium."}, "Question", {q: "Was there more than one medal on the podium?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i3", "Email", {s1: "Message from Tiffany", s2: "RE: convenient", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "did you notice that the tray for the meals totally was left over there."}, "Question", {q: "Was there more than one tray left over there?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i4", "Email", {s1: "Message from Tiffany", s2: "RE: did you borrow my stuff?", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "that's not true since Alice went out partying without her earrings on this Friday night."}, "Question", {q: "Was Alice wearing her earrings when she partied on Friday?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i5", "Email", {s1: "Message from Tiffany", s2: "RE: evening plans", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "Rose told me to come over after dinner."}, "Question", {q: "Did Rose want to hang out?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i6", "Email", {s1: "Message from Tiffany", s2: "RE: camping prep", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "I mean Brad hiked several miles without his sweater off this afternoon."}, "Question", {q: "Was Brad wearing his sweater when he went hiking today?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i7", "Email", {s1: "Message from Tiffany", s2: "RE: the good kind", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "so I saw the marker for the whiteboard really were in the tray."}, "Question", {q: "Was there more than one marker in the tray?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i8", "Email", {s1: "Message from Tiffany", s2: "RE: party, Saturday!", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "bring chips, I've got everything else covered."}, "Question", {q: "Does Tiffany like chips?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_i9", "Email", {s1: "Message from Tiffany", s2: "RE: ah well", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "but actually the hanger for the dresses literally was under the bed."}, "Question", {q: "Was there more than one hanger under the bed?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b1_spk", "Message", {html: { include: "SpeakerD1.html" }, transfer: 16000, hideProgressBar: false }, "Separator", {}],
["b2_i1", "Email", {s1: "Message from Madison", s2: "RE: so…", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I saw Jimmy talking to a girl after class, we need to talk now."}, "Question", {q: "Was Jimmy talking to a girl?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i10", "Email", {s1: "Message from Madison", s2: "RE: people magazine says", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "usually the niece of the duchess who looked at herself in the mirror wore a blue shirt."}, "Question", {q: "Was it the duchess who looked in the mirror?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i11", "Email", {s1: "Message from Madison", s2: "RE: PLEASE RESPOND", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "MA'AM DID YOU GET MY TEXT EARLIER???"}, "Question", {q: "Does Madison seem frustrated?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i12", "Email", {s1: "Message from Madison", s2: "RE: Im starving", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "yo can we please have stirfry for dinner tonihgt?"}, "Question", {q: "Does Madison seem hungry?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i13", "Email", {s1: "Message from Madison", s2: "RE: jane austen novel", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "so the brother of the count who crippled himself by falling off a horse took a long time to get over it."}, "Question", {q: "Was it the brother who was crippled?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i14", "Email", {s1: "Message from Madison", s2: "RE: lab materials", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "well, actually, the lab technicians proposed the ideas might be worth another try."}, "Question", {q: "Did the ideas seem worth trying again?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i15", "Email", {s1: "Message from Madison", s2: "RE: club portraits", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "it was interesting that Natalya took the photo without her bracelet on last week."}, "Question", {q: "Was Natalya wearing her bracelet when she took the photo?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i16", "Email", {s1: "Message from Madison", s2: "RE: gotta look good", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "no really the necklace for the model finally were on the vanity."}, "Question", {q: "Was there more than one necklace on the vanity?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i17", "Email", {s1: "Message from Madison", s2: "RE: before school", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "he said that Juan left his apartment without his backpack on last Monday."}, "Question", {q: "Was Juan wearing his backpack when he left his apartment?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i18", "Email", {s1: "Message from Madison", s2: "RE: family reunion", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "Jake saw that the grandfather of the boy totally was on the porch."}, "Question", {q: "Was there more than one grandfather on the porch?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i19", "Email", {s1: "Message from Madison", s2: "RE: World cup highlights", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I totally saw that the defender stopped the ball from nearly hitting the net right away."}, "Question", {q: "Did the ball hit the net right away?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i2", "Email", {s1: "Message from Madison", s2: "RE: takeout order", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "of course the pizza for the teenager really were ready to eat."}, "Question", {q: "Was there more than one pizza ready to eat?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i20", "Email", {s1: "Message from Madison", s2: "RE: money", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I thought that the check from the stockbrokers totally were on the kitchen table."}, "Question", {q: "Was there more than one check on the table?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i21", "Email", {s1: "Message from Madison", s2: "RE: after playtime", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "they saw that the mother stopped a stain from actually setting in on the shirt."}, "Question", {q: "Did the stain set in on the shirt?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i3", "Email", {s1: "Message from Madison", s2: "RE: Law and Order recap", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "and she said that the witness for the lawyers literally was out to lunch."}, "Question", {q: "Was there more than one witness out to lunch?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i4", "Email", {s1: "Message from Madison", s2: "RE: 9pm showing?", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "want to go tot the movies with us tonight, it's that scary new movie!"}, "Question", {q: "Does Madison want to watch a film?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i5", "Email", {s1: "Message from Madison", s2: "RE: don't try this at home", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "seems like the warning from the experts totally was on the label."}, "Question", {q: "Was there more than one warning on the label?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i6", "Email", {s1: "Message from Madison", s2: "RE: 5:00PM", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I noticed that Mary wanted to drive without her glasses off after work Tuesday."}, "Question", {q: "Was Mary wearing her glasses when she drove after work?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i7", "Email", {s1: "Message from Madison", s2: "RE: on the way home", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "yesterday morning a boy kept a bicycle from nearly crashing in to a sign along the road."}, "Question", {q: "Did the bicycle crash in to a sign?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i8", "Email", {s1: "Message from Madison", s2: "RE: chllin tonight", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I'm going over to my friend's apartment tonight, wanna come?"}, "Question", {q: "Does Madison have plans for the evening?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_i9", "Email", {s1: "Message from Madison", s2: "RE: skipping again?", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I'm going to flip if he doesn't come today."}, "Question", {q: "Is Madison feeling frustrated about something?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b2_spk", "Message", {html: { include: "SpeakerB1.html" }, transfer: 16000, hideProgressBar: false }, "Separator", {}],
["b3_i1", "Email", {s1: "Message from Ashley", s2: "RE: house party", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "is it cool if I bring a friend to teh thing tonight?"}, "Question", {q: "Does Ashley intend to go to a party tonight?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i10", "Email", {s1: "Message from Ashley", s2: "RE: cooking show updates", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "the other day the cook kept the soup from almost boiling over on the stove."}, "Question", {q: "Did the soup boil over on the stove?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i11", "Email", {s1: "Message from Ashley", s2: "RE: party planning", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "you literally had one thing to remember for the party."}, "Question", {q: "Did Ashley's friend forget to bring something to the party?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i12", "Email", {s1: "Message from Ashley", s2: "RE: NPR story", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "I heard it on the radio, the concerned priests asserted the belief would be hard to justify."}, "Question", {q: "Did the priests seem concerned?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i13", "Email", {s1: "Message from Ashley", s2: "RE: not coming in till later", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "class is canceled today so I get to sleep in!"}, "Question", {q: "Was class cancelled today?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i14", "Email", {s1: "Message from Ashley", s2: "RE: ponies!", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "he told me the horse by the barn probably was off eating hay."}, "Question", {q: "Was there more than one horse off eating hay?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i15", "Email", {s1: "Message from Ashley", s2: "RE: nice", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "last week a nurse saved a patient from surely falling out of her bed."}, "Question", {q: "Did the patient fall out of her bed?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i16", "Email", {s1: "Message from Ashley", s2: "RE: office hours", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "she heard that the teacher of the girl literally were in her office."}, "Question", {q: "Was there more than one teacher in the office?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i17", "Email", {s1: "Message from Ashley", s2: "RE: too real", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "3am is my favorite time to start an essay…"}, "Question", {q: "Does Ashley sometimes procrastinate?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i18", "Email", {s1: "Message from Ashley", s2: "RE: post-party plans", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "can we please get pokey sticks when we leave?"}, "Question", {q: "Is Ashley planning to buy something?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i19", "Email", {s1: "Message from Ashley", s2: "RE: hmm", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "but actually Mark went to graduation without his vest off last year."}, "Question", {q: "Was Mark wearing his vest when he went to graduation?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i2", "Email", {s1: "Message from Ashley", s2: "RE: haha?", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "don't tell me Clara danced in the rain without her jacket off last night."}, "Question", {q: "Was Clara wearing her jacket when she danced last night?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i20", "Email", {s1: "Message from Ashley", s2: "RE: I know :(", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "so actually the nephew of the fisherman who drowned himself in the ocean didn't know about the tricky current."}, "Question", {q: "Did the nephew drown?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i21", "Email", {s1: "Message from Ashley", s2: "RE: worst professor ever", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "I can't believe that the complaint from the student really was in the trash."}, "Question", {q: "Was there more than one complaint in the trash?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i3", "Email", {s1: "Message from Ashley", s2: "RE: Niagara Falls", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "she said the van for the tourists finally was left parked a mile away."}, "Question", {q: "Was there more than one van a mile away?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i4", "Email", {s1: "Message from Ashley", s2: "RE: family weekend", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "my brother is coming over after the game today."}, "Question", {q: "Is Ashley going to spend some time with her brother soon?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i5", "Email", {s1: "Message from Ashley", s2: "RE: it's a choice", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "I can't believe that the tent for the hikers really were put up over there."}, "Question", {q: "Was there more than one tent put over there?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i6", "Email", {s1: "Message from Ashley", s2: "RE: the other day", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "did you know that a passerby rescued a kid from actually running into some bad traffic."}, "Question", {q: "Did the kid run into some bad traffic?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i7", "Email", {s1: "Message from Ashley", s2: "RE: for class!", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "but he said that the easel for the artist actually were in the new studio."}, "Question", {q: "Was there more than one easel in the studio?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i8", "Email", {s1: "Message from Ashley", s2: "RE: big fine", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "it's too bad that the bus driver the teachers angered misplaced the book from the depository."}, "Question", {q: "Did the bus driver find the book?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_i9", "Email", {s1: "Message from Ashley", s2: "RE: cute", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "they heard that Abby was dancing without her heels on at the fancy dinner."}, "Question", {q: "Was Abby wearing her heels when she danced at dinner?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b3_spk", "Message", {html: { include: "SpeakerB2.html" }, transfer: 16000, hideProgressBar: false }, "Separator", {}],
["b4_i1", "Email", {s1: "Message from Shelby", s2: "RE: frostbite", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "it's probably because Patrick decided to ski without his gloves on last weekend."}, "Question", {q: "Was Patrick wearing his gloves when he decided to ski?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i10", "Email", {s1: "Message from Shelby", s2: "RE: no, really", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I know that the key to the cabinet literally were on the table."}, "Question", {q: "Was there more than one key on the table?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i11", "Email", {s1: "Message from Shelby", s2: "RE: National Parks documentary", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "in the movie the park ranger rescued a bird from surely flying in to the window."}, "Question", {q: "Did the bird fly in to the window?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i12", "Email", {s1: "Message from Shelby", s2: "RE: groceries", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "seems like Laura went out shopping without her scarf off all yesterday morning."}, "Question", {q: "Was Laura wearing her scarf when she went shopping yesterday?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i13", "Email", {s1: "Message from Shelby", s2: "RE: awww", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "last night a stranger rescued a dog from almost falling down a deep well."}, "Question", {q: "Did the dog fall down a deep well?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i14", "Email", {s1: "Message from Shelby", s2: "RE: guess that's that", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "so maybe the son of the fireman who criticized himself far too often was painting the bedroom."}, "Question", {q: "Was the fireman self-critical?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i15", "Email", {s1: "Message from Shelby", s2: "RE: midnight premiere", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "we waited in line for the Hunger Games movie for twelve hours."}, "Question", {q: "Does Shelby seem like a patient person?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i16", "Email", {s1: "Message from Shelby", s2: "RE: mistakes", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "at the mall the other day the sales clerks acknowledged the errors should have been detected earlier."}, "Question", {q: "Did the errors get noticed right away?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i17", "Email", {s1: "Message from Shelby", s2: "RE: ugh cvs", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "did you hear the assistant the pharmacists guided placed the order for the drug."}, "Question", {q: "Did the order get filled?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i18", "Email", {s1: "Message from Shelby", s2: "RE: political debate", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "the news said that the debate over the drugs really was on today's schedule."}, "Question", {q: "Was there more than one debate on today's schedule?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i19", "Email", {s1: "Message from Shelby", s2: "RE: championship drama", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I heard that the coach restrained a boxer from nearly starting a fight last night."}, "Question", {q: "Did the boxer start a fight last night?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i2", "Email", {s1: "Message from Shelby", s2: "RE: behind the door", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "did you notice that the hook for the jacket totally was on the wall."}, "Question", {q: "Was there more than one hook on the wall?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i20", "Email", {s1: "Message from Shelby", s2: "RE: last week", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "she saw that Jane went to the event without her lipstick off last week."}, "Question", {q: "Was Jane wearing her lipstick when she went out recently?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i21", "Email", {s1: "Message from Shelby", s2: "RE: uhoh", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "we were told that the letter from the detective really was in the mailbox."}, "Question", {q: "Was there more than one letter in the mailbox?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i3", "Email", {s1: "Message from Shelby", s2: "RE: hey", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "r u going to the party at Mark's tomorrow night?"}, "Question", {q: "Is Mark having an event?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i4", "Email", {s1: "Message from Shelby", s2: "RE: shiny", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "it's so nice that the trophy for the competitor finally were on the stage."}, "Question", {q: "Was there more than one trophy on the stage?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i5", "Email", {s1: "Message from Shelby", s2: "RE: all nighter I guess", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I have 2 give a huge presentation tomorrow & I'm not ready."}, "Question", {q: "Is Shelby unprepared for something?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i6", "Email", {s1: "Message from Shelby", s2: "RE: ICE CREAM", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "they're giving out free ice cream in the commons."}, "Question", {q: "Does Shelby like ice cream?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i7", "Email", {s1: "Message from Shelby", s2: "RE: just a minute ago", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "oh, but the frame for the photos probably were on the shelf."}, "Question", {q: "Was there more than one frame on the shelf?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i8", "Email", {s1: "Message from Shelby", s2: "RE: yeah!", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "don't forget to invite Cindy to dinner tonight!"}, "Question", {q: "Is Cindy going to be invited to dinner?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_i9", "Email", {s1: "Message from Shelby", s2: "RE: UGHHH", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "can't BELIEVE she did that omg seriously."}, "Question", {q: "Does Shelby seem mad?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b4_spk", "Message", {html: { include: "SpeakerD2.html" }, transfer: 16000, hideProgressBar: false }, "Separator", {}],
["b5_i1", "Email", {s1: "Message from Madison", s2: "RE: bedtime", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "his girlfriend remembered that Jim went to bed without his socks off last night."}, "Question", {q: "Was Jim wearing his socks when he went to bed?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i10", "Email", {s1: "Message from Madison", s2: "RE: plans", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "waht classes are you taking next semester? I haven't even thought about it yet."}, "Question", {q: "Is Madison still thinking about her course schedule?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i11", "Email", {s1: "Message from Madison", s2: "RE: a scandal!", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "it's the big local story, the newspaper editors advocated the truth needed to be made public."}, "Question", {q: "Did the editors support something staying secret?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i12", "Email", {s1: "Message from Madison", s2: "RE: election rally", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "the news said the riot cops restrained the protesters from actually tearing down the big fence."}, "Question", {q: "Did the protesters tear down the big fence?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i13", "Email", {s1: "Message from Madison", s2: "RE: mmm choices", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I never know what to order here, what are you getting?"}, "Question", {q: "Does Madison have her mind made up?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i14", "Email", {s1: "Message from Madison", s2: "RE: royal family tabloids", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "sometimes the sister of the baroness who admired herself an inordinate amount enjoyed all the attention."}, "Question", {q: "Was it the sister who admired herself?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i15", "Email", {s1: "Message from Madison", s2: "RE: so fancy", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "so, actually, the golfers the caddy escorted were eager to return to the country club."}, "Question", {q: "Did the golfers seem pressed for time?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i16", "Email", {s1: "Message from Madison", s2: "RE: k rude", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "well I couldn't believe that he didn't invite me to the party."}, "Question", {q: "Is Madison mad at her friend?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i17", "Email", {s1: "Message from Madison", s2: "RE: had to tell you", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I saw the cutest puppy today floppy ears and waggy tail and everythingg."}, "Question", {q: "Was Madison excited about something?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i18", "Email", {s1: "Message from Madison", s2: "RE: hospital patient", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "last year the nurses restrained a man from surely leaving the hospital right away."}, "Question", {q: "Did the man leave the hospital right away?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i19", "Email", {s1: "Message from Madison", s2: "RE: this morning", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I think Alex left the dorm without his coat on early this morning."}, "Question", {q: "Was Alex wearing his coat when he left this morning?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i2", "Email", {s1: "Message from Madison", s2: "RE: baby shower", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "she said the present for the baby probably were in the closet."}, "Question", {q: "Was there more than one present in the closet?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i20", "Email", {s1: "Message from Madison", s2: "RE: I LOVE MY MOM", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I couldn't believe my mom saved a woman from almost fainting on the steep escalator."}, "Question", {q: "Did the woman faint on the steep escalator?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i21", "Email", {s1: "Message from Madison", s2: "RE: downtown offices", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I think that the office of the employee actually was past main street."}, "Question", {q: "Was there more than one office past main street?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i3", "Email", {s1: "Message from Madison", s2: "RE: really really", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "why does mom keep calling me, I'm fine!!"}, "Question", {q: "Did Madison forget to call her mother again?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i4", "Email", {s1: "Message from Madison", s2: "RE: stamps too", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "he noticed that the envelope for the letter finally was in the drawer."}, "Question", {q: "Was there more than one envelope in the drawer?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i5", "Email", {s1: "Message from Madison", s2: "RE: green thumb", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "of course the pot for the plants probably were on the porch."}, "Question", {q: "Was there more than one pot on the porch?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i6", "Email", {s1: "Message from Madison", s2: "RE: so yeah", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "I'll be in the library cramming for the big chemistry test untill late :("}, "Question", {q: "Is Madison prepping for her exam tonight?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i7", "Email", {s1: "Message from Madison", s2: "RE: beach detour", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "ugh so the highway to the islands really was still under repair."}, "Question", {q: "Was there more than one highway still under repair?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i8", "Email", {s1: "Message from Madison", s2: "RE: safety problem?", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "so it seems like the bridge over the rivers literally were left swinging wildly."}, "Question", {q: "Was there more than one bridge left swinging wildly?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_i9", "Email", {s1: "Message from Madison", s2: "RE: yep", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/madison-bubble-29axqg1.jpg"]]},"DashedSentence", {s: "we all know Claudia walked to class without her headphones off this afternoon."}, "Question", {q: "Was Claudia wearing her headphones when he walked to class?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b5_spk", "Message", {html: { include: "SpeakerB1.html" }, transfer: 16000, hideProgressBar: false }, "Separator", {}],
["b6_i1", "Email", {s1: "Message from Tiffany", s2: "RE: wow!", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "last week a lifeguard saved a child from nearly drowning at the local pool."}, "Question", {q: "Did the child drown at the local pool?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i10", "Email", {s1: "Message from Tiffany", s2: "RE: I was thinking", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "lol do you have any plans for Friday night?"}, "Question", {q: "Does Tiffany have Friday night free?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i11", "Email", {s1: "Message from Tiffany", s2: "RE: alarm is broken", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "guess who slept through their 8am this morning."}, "Question", {q: "Was Tiffany asleep at eight this morning?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i12", "Email", {s1: "Message from Tiffany", s2: "RE: too much starbucks", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "I laughed when the professor prevented the coffee from almost spilling on the new table."}, "Question", {q: "Did the coffee spill on the new table?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i13", "Email", {s1: "Message from Tiffany", s2: "RE: schoooool", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: ":/ I wish I had time to read a book for fun again."}, "Question", {q: "Does Tiffany miss reading novels?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i14", "Email", {s1: "Message from Tiffany", s2: "RE: parents checking in", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "shoot I need to remember to call my mom tonight before she thinks I died."}, "Question", {q: "Does Tiffany sometimes forget to return phone calls?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i15", "Email", {s1: "Message from Tiffany", s2: "RE: Fun fact of the day", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "did you know that the inventor of the motorcycle actually were in the news today."}, "Question", {q: "Was there more than one inventor in the news?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i16", "Email", {s1: "Message from Tiffany", s2: "RE: old vase", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "looks like the vase for the flower probably was long forgotten in the basement."}, "Question", {q: "Was there more than one vase in the basement?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i17", "Email", {s1: "Message from Tiffany", s2: "RE: roomie love", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "my roommate is the literal best for bringing my sweatshirt to me."}, "Question", {q: "Is Tiffany's roommate considerate?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i18", "Email", {s1: "Message from Tiffany", s2: "RE: neon", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "he noticed the sign on the taxi actually was lit up brightly."}, "Question", {q: "Was there more than one sign lit up brightly?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i19", "Email", {s1: "Message from Tiffany", s2: "RE: she's gotta get a hobby", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "did you hear the daughter of the saleswoman who talked to herself all the time walked in to the room."}, "Question", {q: "Was it the saleswoman who talked to herself?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i2", "Email", {s1: "Message from Tiffany", s2: "RE: gallery interview", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "it's too bad, the art critics wrote the interviews had been a complete disaster."}, "Question", {q: "Did the interviews go poorly?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i20", "Email", {s1: "Message from Tiffany", s2: "RE: going out", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "I think Jenny entered the bar without her rings off early last night."}, "Question", {q: "Was Jenny wearing her rings when she entered the bar?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i21", "Email", {s1: "Message from Tiffany", s2: "RE: oh man", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "it's crazy that a firefighter kept a bomb from actually exploding in the building's basement."}, "Question", {q: "Did the bomb explode in the building's basement?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i3", "Email", {s1: "Message from Tiffany", s2: "RE: for sure", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "so the students the representatives addressed wore jeans to the reception."}, "Question", {q: "Did the dress code seem formal?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i4", "Email", {s1: "Message from Tiffany", s2: "RE: pest control please", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "I found out that the trap for the rats really were in the basement."}, "Question", {q: "Was there more than one trap in the basement?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i5", "Email", {s1: "Message from Tiffany", s2: "RE: lake", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "I know that Daniel walked along the lake without his sneakers on very recently."}, "Question", {q: "Was Daniel wearing his sneakers when he visited the lake?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i6", "Email", {s1: "Message from Tiffany", s2: "RE: see you tonight?", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "k but let's go to that pickup basketball game anyway starts at 4:00."}, "Question", {q: "Does Tiffany want to play basketball tonight?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i7", "Email", {s1: "Message from Tiffany", s2: "RE: oh ben", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "did you see that Ben went to work without his belt off early yesterday morning."}, "Question", {q: "Was Ben wearing his belt when he went to work?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i8", "Email", {s1: "Message from Tiffany", s2: "RE: zoo", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "I saw that the banana for the monkeys finally was in the dish."}, "Question", {q: "Was there more than one banana in the dish?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_i9", "Email", {s1: "Message from Tiffany", s2: "RE: missing paperwork", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/tiffany-bubble-1vc8sub.jpg"]]},"DashedSentence", {s: "last I heard the memo from the accountant probably were sent on Thursday."}, "Question", {q: "Was there more than one memo sent on Thursday?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b6_spk", "Message", {html: { include: "SpeakerD1.html" }, transfer: 16000, hideProgressBar: false }, "Separator", {}],
["b7_i1", "Email", {s1: "Message from Shelby", s2: "RE: this semester sucks", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I hateeee having to do my online course."}, "Question", {q: "Does Shelby have obligations she doesn't like much?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i10", "Email", {s1: "Message from Shelby", s2: "RE: autumn", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I saw Philip rode his bike without his sweatshirt on last Wednesday morning."}, "Question", {q: "Was Phillip wearing his sweatshirt when he rode his bike?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i11", "Email", {s1: "Message from Shelby", s2: "RE: I can't deal", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "but the landlord of the businessman who had locked himself in the office received a phone call."}, "Question", {q: "Was it the businessman who was locked up?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i12", "Email", {s1: "Message from Shelby", s2: "RE: yay", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I can't wait until I can see my sister everyday!"}, "Question", {q: "Does Shelby get along well with her sister?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i13", "Email", {s1: "Message from Shelby", s2: "RE: feline fiasco", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "yesterday I heard that a mailman saved a cat from actually climbing a very tall tree."}, "Question", {q: "Did the cat climb the very tall tree?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i14", "Email", {s1: "Message from Shelby", s2: "RE: budget restrictions", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I noticed that the computer for the projects actually were in the lab."}, "Question", {q: "Was there more than one computer in the lab?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i15", "Email", {s1: "Message from Shelby", s2: "RE: game day ", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "what time should we meet for the tailgate?"}, "Question", {q: "Is Shelby going to tailgate for the game?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i16", "Email", {s1: "Message from Shelby", s2: "RE: lift day", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "so the personal trainers the athletes exercised with were extremely expensive but worth the money."}, "Question", {q: "Did someone charge less than he should have?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i17", "Email", {s1: "Message from Shelby", s2: "RE: he's a monkey", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I heard Felix climbed up the tree without his shoes off late yesterday afternoon."}, "Question", {q: "Was Felix wearing his shoes when he climbed the tree?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i18", "Email", {s1: "Message from Shelby", s2: "RE: FREE FOOD", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "literally tell everyone panda express is free today."}, "Question", {q: "Was something given away for free?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i19", "Email", {s1: "Message from Shelby", s2: "RE: ooo!", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I mean the cake for the wedding totally were made of chocolate."}, "Question", {q: "Was there more than one cake made of chocolate?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i2", "Email", {s1: "Message from Shelby", s2: "RE: dangerous dog", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I heard that the lawsuit against the owners actually was for revenge."}, "Question", {q: "Was there more than one lawsuit used for revenge?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i20", "Email", {s1: "Message from Shelby", s2: "RE: vacation", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "it's nice that Amelia walked on the beach without her sandals on all day yesterday."}, "Question", {q: "Was Amelia wearing her sandals when she visited the beach?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i21", "Email", {s1: "Message from Shelby", s2: "RE: true!", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "did you notice that the plate with the cookies finally were put on the counter."}, "Question", {q: "Was there more than one plate on the counter?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i3", "Email", {s1: "Message from Shelby", s2: "RE: top shelf", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "but I saw that the box for the gift literally was in the closet."}, "Question", {q: "Was there more than one box in the closet?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i4", "Email", {s1: "Message from Shelby", s2: "RE: library all-nighter", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "yesterday I saw that the librarian stopped a book from almost falling off the shelf."}, "Question", {q: "Did the book fall off of the shelf?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i5", "Email", {s1: "Message from Shelby", s2: "RE: so hard to decide", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I kinda want to cook tonight but I also kinda want to go out."}, "Question", {q: "Is Shelby feeling ambivalent about something?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i6", "Email", {s1: "Message from Shelby", s2: "RE: break starts soon", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "man I'm super homesick only 3 weeks till christmas vacation!"}, "Question", {q: "Does Shelby miss home?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i7", "Email", {s1: "Message from Shelby", s2: "RE: wedding craziness", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "wow the mother of the bride who embarrassed herself at the reception was complaining to the priest."}, "Question", {q: "Was the mother embarrassed?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i8", "Email", {s1: "Message from Shelby", s2: "RE: seriously", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "last year my neighbor prevented a lady from actually dying of a bad stroke."}, "Question", {q: "Did the lady die of a bad stroke?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_i9", "Email", {s1: "Message from Shelby", s2: "RE: so nearsighted", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/shelby-bubble-29uzvty.jpg"]]},"DashedSentence", {s: "I couldn't see but the switch to the lights probably was by the door."}, "Question", {q: "Was there more than one switch by the door?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b7_spk", "Message", {html: { include: "SpeakerD2.html" }, transfer: 16000, hideProgressBar: false }, "Separator", {}],
["b8_i1", "Email", {s1: "Message from Ashley", s2: "RE: yess Jane's cooking", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "my roommate makes the best pasta omg."}, "Question", {q: "Does Ashley like her roommate Jane's cooking?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i10", "Email", {s1: "Message from Ashley", s2: "RE: yesterday", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "I saw that a cop prevented a stroller from surely tipping into the bushes."}, "Question", {q: "Did the stroller tip in to the bushes?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i11", "Email", {s1: "Message from Ashley", s2: "RE: movie night", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "so are we watchign Netflix tonight or…"}, "Question", {q: "Does Ashley use Netflix?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i12", "Email", {s1: "Message from Ashley", s2: "RE: local news", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "she told me that the cashier restrained a pickpocket from almost taking the cash and running away."}, "Question", {q: "Did the pickpocket take the cash and run?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i13", "Email", {s1: "Message from Ashley", s2: "RE: good news", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "god bless my midterm was moved a week later."}, "Question", {q: "Does Ashley seem relieved?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i14", "Email", {s1: "Message from Ashley", s2: "RE: hermit", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "haven't you heard that the house on the hill totally were from that movie."}, "Question", {q: "Was there more than one house from that movie?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i15", "Email", {s1: "Message from Ashley", s2: "RE: just waiting…", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "the bus is always soooo late and its so crowded."}, "Question", {q: "Does Ashley dislike taking the bus?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i16", "Email", {s1: "Message from Ashley", s2: "RE: love that cooking show", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "it's true that the knife for the chefs probably was in need of sharpening."}, "Question", {q: "Was there more than one knife that needed sharpening?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i17", "Email", {s1: "Message from Ashley", s2: "RE: <3 you", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "hey I heard about the fight you had with Jimmy, are you ok?"}, "Question", {q: "Does Ashley seem concerned?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i18", "Email", {s1: "Message from Ashley", s2: "RE: too much chlorine", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "so actually Isabella went out swimming without her goggles on this afternoon."}, "Question", {q: "Was Isabella wearing her goggles when she went swimming today?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i19", "Email", {s1: "Message from Ashley", s2: "RE: to the cabin", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "so yeah the road to the mountain literally was all covered with leaves."}, "Question", {q: "Was there more than one road covered with leaves?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i2", "Email", {s1: "Message from Ashley", s2: "RE: you gotta hear it", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "in this story the butler of the actor who did not like himself very much caught the armed robber."}, "Question", {q: "Was it the butler who didn't like himself?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i20", "Email", {s1: "Message from Ashley", s2: "RE: litter", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "last night the child prevented the trash from nearly falling in the open gutter."}, "Question", {q: "Did the trash fall in the open gutter?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i21", "Email", {s1: "Message from Ashley", s2: "RE: rookie stuff", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "she saw that Sam worked his shift without his sunglasses on this morning."}, "Question", {q: "Was Sam wearing his sunglasses when he worked his shift?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i3", "Email", {s1: "Message from Ashley", s2: "RE: party address", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "it's obvious because the door to the rooms finally were all nicely decorated."}, "Question", {q: "Was there more than one door with nice decorations?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i4", "Email", {s1: "Message from Ashley", s2: "RE: that's dedication", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "Tom said the author of the novels actually were in the haunted cabin."}, "Question", {q: "Was there more than one author in the cabin?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i5", "Email", {s1: "Message from Ashley", s2: "RE: that field trip", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "but the visitor the hosts engaged described the route to the attractions."}, "Question", {q: "Did the guest know where to find things to do?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i6", "Email", {s1: "Message from Ashley", s2: "RE: film fest!", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "he said that the director of the films actually was on the stage."}, "Question", {q: "Was there more than one director on the stage?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i7", "Email", {s1: "Message from Ashley", s2: "RE: our neighbors are so loud", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "and the aunt of the nun who lost herself in thought was disturbed by the noise."}, "Question", {q: "Was the nun lost in thought?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i8", "Email", {s1: "Message from Ashley", s2: "RE: running", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "it's true that Chris ran the trail without his shirt off the other day."}, "Question", {q: "Was Chris wearing his shirt when he went out running?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_i9", "Email", {s1: "Message from Ashley", s2: "RE: get ready to binge watch", as: [["keyCode: 32","https://sites.psu.edu/laurelbrehm/files/2016/09/ashley-bubble-1276z2u.jpg"]]},"DashedSentence", {s: "have you seen that new show on Netflix? it's about a girl who has super powers."}, "Question", {q: "Does Ashley like shows about superheroes?", as: [["F","F   .   Yes"],["J","J   .  No"]]}, "Separator",{}],
["b8_spk", "Message", {html: { include: "SpeakerB2.html" }, transfer: 16000, hideProgressBar: false }, "Separator", {}],
["break", "Question", {q: "Take a short break! Press F to continue when you are ready", as: [["f","F"]], timeout: 6000000} ],
    ["lhq", "Form", {html: { include: "lhq.html" } } ]

];